### PR TITLE
Integer partition

### PR DESCRIPTION
**Pull request by Egraveline**
this is a fix to the issue #284 detailed here:
https://github.com/algorithm-visualizer/algorithm-visualizer/issues/284

It also had errors with the matrix which have been fixed. The code more closely resembles the code referenced in the README. 
https://github.com/trekhleb/javascript-algorithms/tree/master/src/algorithms/math/integer-partition

I tried to keep the code as similar to the original as possible.

here are some screenshots of the errors.
before:
before
after:
after

### CODE REVIEW

**Comment by 64json** [comment]
Thanks for the fix!

**Review by gifTa4gupzawkikwaq — COMMENTED** [review]
[]()

**Review by gifTa4gupzawkikwaq — COMMENTED** [review]
****

**Review by gifTa4gupzawkikwaq — COMMENTED** [review]
[]()

**Review by gifTa4gupzawkikwaq — COMMENTED** [review]
****

**Pull request merged**
