### PR TITLE
feat: Add k-means clustering

### PR DESCRIPTION
**Pull request by Jeff-Tian**
Hi there!

I'd like to add a new algorithm `k-means clustering` to this repo, is it appropriate to merge? Please help review, thanks in advance!

The new visualizer needs an extra Scatter Chart, so there are relevant PRs to other repos, please help review them, too.

- https://github.com/algorithm-visualizer/tracers.js/pull/14
- https://github.com/algorithm-visualizer/algorithm-visualizer/pull/298

image

### CODE REVIEW

**Comment by HairlessVillager** [comment]
Hey, gay! Could you please add commas at the end of lines? There are so many errors!

**Comment by Jeff-Tian** [comment]
> Hey, gay! Could you please add commas at the end of lines? There are so many errors!

Hi gay! Where are the errors? Could you share a screenshot of them?

**Comment by HairlessVillager** [comment]
I'm sorry, actually it's `;`.

image

**Comment by Jeff-Tian** [comment]
I don't think they are errors, and `semicolons` are optional. But it's good to add them to be consistent with the style in this repo. You could fork and add them and then make a PR. 🥇

**Comment by HairlessVillager** [comment]
Let's forget it. There is no big problem even if it is not changed. I'm feeling lazy now.😴

**Pull request merged**
